databases:
  - name: render-deploy
    plan: free
    databaseName: bookshelter_db
    user: bookshelter_user
    region: oregon

services:
  - type: web
    name: BookShelter
    env: node
    branch: main
    buildCommand: npm run render-seed
    startCommand: npm start
    envVars:
      - key: DB_URL
        fromDatabase: # automatically injects the DB connection string to the DB_URL environment
          name: render-deploy # Must match the database deployment's name
          property: connectionString
